In [1]:
import numpy as np

In [3]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [5]:
#在0-10中随机生成三行三列的数据
a=np.random.randint(0,10,size=(3,3))
a

array([[4, 3, 7],
       [1, 8, 4],
       [9, 3, 9]])

In [6]:
np.argwhere(a>5)

array([[0, 2],
       [1, 1],
       [2, 0],
       [2, 2]], dtype=int64)

### 概念没看懂。。。

In [ ]:
#读取数据
data = pd.read_csv('student_data.csv')
data[:10]