In [1]:
import numpy as np

In [2]:
A = np.mat([[4,5,6],[1,2,3]]) # 生成矩阵

In [3]:
A

matrix([[4, 5, 6],
        [1, 2, 3]])

In [4]:
U = A * A.T # 矩阵与矩阵转置相乘，得到一个方阵

In [5]:
U

matrix([[77, 32],
        [32, 14]])

In [7]:
np.linalg.eig(U)

(array([90.40267253,  0.59732747]), matrix([[ 0.92236578, -0.3863177 ],
         [ 0.3863177 ,  0.92236578]]))