In [1]:
import numpy as np

In [2]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [3]:
tran_arr = np.transpose(arr,axes=None)
tran_arr

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [4]:
arr.T # 对于一维数组来说，其实就是线性代数的转置矩阵

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## 三维数组

In [5]:
arr3 = np.arange(12).reshape(2,2,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
# 索引示例
print(arr3[1,1,0])
print(arr3[0,1,0])
print(arr3[1,0,2])

9
3
8


In [13]:
tran_arr3 = np.transpose(arr3, (1, 0, 2))  # （1， 0， 2）为索引号

In [17]:
print("arr3")
print(arr3)
print("*"*20)
print("tran_arr3")
print(tran_arr3)

arr3
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
********************
tran_arr3
[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]


In [20]:
arr4 = np.arange(24).reshape(3,4,2)
tran_arr4 = np.transpose(arr4,(1,0,2))

In [21]:
print("arr4")
print(arr4)
print("*"*20)
print("tran_arr4")
print(tran_arr4)

arr4
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
********************
tran_arr4
[[[ 0  1]
  [ 8  9]
  [16 17]]

 [[ 2  3]
  [10 11]
  [18 19]]

 [[ 4  5]
  [12 13]
  [20 21]]

 [[ 6  7]
  [14 15]
  [22 23]]]


上面的shape 由(3,4,2)变成了(4,3,2)，不就是因为索引号由（0,1,2）变成了（1,0,2）吗？

转置就是这么简单！