In [1]:
import numpy as np

## np.random.randn()

numpy.random.randn(d0,d1,…,dn)

randn函数返回一个或一组样本，具有标准正态分布。<br>
dn表格每个维度<br>
返回值为指定维度的array

In [2]:
#1)当函数括号内没有参数时，则返回一个浮点数； 
np.random.randn()

-1.8986461893833941

In [5]:
#2）当函数括号内有一个参数时，则返回秩为1的数组，不能表示向量和矩阵；
print(np.random.randn(1))
print(np.random.randn(2))

[0.5470764]
[-0.81659007  1.14615294]


In [6]:
#3）当函数括号内有两个及以上参数时，则返回对应维度的数组，能表示向量或矩阵； 
np.random.randn(5,2)

array([[ 0.77347398,  0.48035216],
       [-1.11673746, -0.06345149],
       [-0.66395206, -0.06699265],
       [-1.08691606,  1.84247621],
       [-0.71903615, -0.59723285]])

In [7]:
2.5 * np.random.randn(2, 4) + 3

array([[ 4.34678101,  2.25666903,  4.78440823,  2.66702989],
       [ 4.8859085 ,  6.96102892, -3.8855928 ,  7.38598434]])

4）np.random.standard_normal（）函数与np.random.randn()类似，但是np.random.standard_normal（）的输入参数为元组（tuple）. <br>
5)np.random.randn()的输入通常为整数，但是如果为浮点数，则会自动直接截断转换为整数。

In [9]:
#numpy.random.standard_normal 
s = np.random.standard_normal(80)
s.shape

(80,)

In [12]:
s1 = np.random.standard_normal(size=(3, 4, 2))
s1.shape

(3, 4, 2)

##### 应用场景：在神经网络构建中，权重参数W通常采用该函数进行初始化，当然需要注意的是，通常会在生成的矩阵后面乘以小数，比如0.01，目的是为了提高梯度下降算法的收敛速度。 
W = np.random.randn(2,2)*0.01

## np.random.rand()函数

注：使用方法与np.random.randn()函数相同  <br>
作用： 
通过本函数可以返回一个或一组服从“0~1”均匀分布的随机样本值。随机样本取值范围是[0,1)，不包括1。 
应用：在深度学习的Dropout正则化方法中，可以用于生成dropout随机向量（dl），例如（keep_prob表示保留神经元的比例）：dl = np.random.rand(al.shape[0],al.shape[1])

In [13]:
np.random.rand()

0.46836204362708267

In [14]:
np.random.rand(1)

array([0.44311953])

In [15]:
np.random.rand(2)

array([0.76732461, 0.53859977])

In [16]:
np.random.rand(3,3)

array([[0.80252438, 0.51034698, 0.46845051],
       [0.76357389, 0.00215437, 0.52342697],
       [0.00219043, 0.47960688, 0.79647409]])

In [17]:
np.random.rand(5,2)

array([[0.81474802, 0.48004426],
       [0.1378261 , 0.06292704],
       [0.569476  , 0.84871126],
       [0.06027516, 0.74095856],
       [0.68691168, 0.75943329]])

### np.random.randint()函数

numpy.random.randint(low, high=None, size=None, dtype=’l’) 
输入： 
low—–为最小值 
high—-为最大值 
size—–为数组维度大小 
dtype—为数据类型，默认的数据类型是np.int。 <br>
返回值： 
返回随机整数或整型数组，范围区间为[low,high），包含low，不包含high； 
high没有填写时，默认生成随机数的范围是[0，low）

In [20]:
np.random.randint(1) 
# low=1 ，输出范围[0,1)内的一个整数

0

In [21]:
# low=1,high=none,size=2.输出范围[0,1)内的一个整数数组
np.random.randint(1,size=(2,2))

array([[0, 0],
       [0, 0]])

In [24]:
#输出[0,2)之间的整数
np.random.randint(0,2)

0

In [25]:
np.random.randint(1,20,size=(4,4),dtype='uint8')

array([[15, 16,  6,  7],
       [ 4, 13, 16, 18],
       [15, 18, 11,  2],
       [13, 16, 13, 10]], dtype=uint8)

### numpy.random.seed()

np.random.seed()的作用：使得随机数据可预测。 <br>
当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数

In [27]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [28]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [29]:
np.random.rand(5)

array([0.96537912, 0.46218718, 0.71936643, 0.50402396, 0.90558239])